### ISSUE TITLE
TError = unknown

### ISSUE THREAD

**Issue by GaiusValerius** [rametta/rapini#15]
Hi,
thank you very much for this great library.

I noticed that you're defining all generics by React-Query but didn't provide AxiosError as TError.

**Comment by rametta** [comment]
@KennethVeipert Yes, that is a good question. To my understanding it seems like the error could either be `Error | AxiosError` based on this comment https://github.com/axios/axios/issues/3612#issuecomment-770224236. I encourage you to open a PR with details on the behaviour of the Axios Error type. I can help review the PR
