### ISSUE TITLE
error trying to run

### ISSUE THREAD

**Issue by gavinthomas-valtech** [rametta/rapini#29]
Have run through the commands in the readme only i get an error when trying to run against react query 4

running node 16.17.0
npm 8.15.0

```px rapini react-query -p openapi.yaml -n VC ```

```DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createParameterDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createFunctionDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
/Users//node_modules/rapini/dist/common/util.js:253
        .split("-")
         ^

TypeError: Cannot read properties of undefined (reading 'split')
    at normalizeOperationId (/Users/node_modules/rapini/dist/common/util.js:253:10)```

**Comment by rametta** [comment]
Hi @gavinthomas-valtech , it seems like the `normalizeOperationId` function is failing - I'm guessing it's because one or many of your endpoints do not have an `operationId` defined in the OpenAPI file, which is the only requirement needed to run.

Can you confirm if that is the case? Thanks

**Comment by gavinthomas-valtech** [comment]
hiya. For each endpoint described there is an operationId. UNless there needs to be a top level one?

I've run the yaml file against other openapi generators and they seem to work okay.

**Comment by rametta** [comment]
Would you be able to paste your open api file? Would help debug

**Comment by rametta** [comment]
Also based on your description that you want v4 react query, you'll need to pass in the v4 flag to the cli command `npx rapini react-query v4 -p path/to/openapi.yaml` but that's unrelated to your issue I foresee. Would still need to see your openapi to help more

**Comment by rametta** [comment]
Will close this issue for now, please reopen if it's still an issue

**Comment by cn-johndpope** [comment]
this problem is fixable by bailing out of this method if the operationId is undefined. 
https://github.com/rametta/rapini/pull/34
