### ISSUE TITLE
clarity on what is needed to correctly create react hook

### ISSUE THREAD

**Issue by cn-johndpope** [rametta/rapini#35]
To be upfront - I'm not sure if my react-native code is faulty - or the yaml  or  index code generated....

I have this method - 
```yaml
  /api/health/ping:
   
    get:
      operationId: "getPing"
      tags:
      - Health
      responses:
        200:
          description: Success
          content: {}

```

it declares stuff as unknown

I get the impression - that we should warn users when they get this unknown model returened to bring attention to fix things first.

    readonly getPing: () => Promise<unknown>;

 readonly useGetPing: (options?: Omit<UseQueryOptions<unknown, unknown, unknown, readonly ["getPing"]>, "queryKey" | "queryFn">) => UseQueryResult<unknown, unknown>;
       

```typescript

const axiosInstance:AxiosInstance = axios.create({
  baseURL: "https://api.setflow.com/",
  timeout: 3000,
  timeoutErrorMessage: 'Server down.. Please try after sometime.',
});
console.log("axiosInstance:",axiosInstance);
console.log("initialize:",initialize);
const config = initialize(axiosInstance);
const { useGetPing } = config.queries;
console.log("useGetPing:",useGetPing);


```

when I implement 

```

function Ping() {
  const { data:any, isLoading, isError } = useGetPing();

  return (
    <div>
      <h1>Ping</h1>

      <div

      >
        {isLoading ? (
          <span>Loading...</span>
        ) : isError ? (
       "error"
        ) : (
         "ok"
        )}
      </div>
    </div>
  )
}

```

<Ping></Ping>

<img width="918" alt="Screenshot 2023-04-01 at 1 50 08 am" src="https://user-images.githubusercontent.com/127367212/229154303-a98f04e5-3fdd-4675-940f-4b41921255ed.png">

then I end up here....
<img width="675" alt="Screenshot 2023-04-01 at 1 50 41 am" src="https://user-images.githubusercontent.com/127367212/229154454-2445124b-9dcb-4c53-b6ad-323335cabaf1.png">

is it the unknown return type - 

I'll have to cross reference the pets yaml.

**Comment by rametta** [comment]
@cn-johndpope no the runtime error is not related to the typescript type. If you see `unknown` it means the yaml is not properly specifying the response return types. I can see from your example that your response content is just `{}` so that is empty and produces the `unknown`. But this is unrelated to your react native crash.

Add the response types to your yaml and you'll get the proper typescript types inferred

**Comment by rametta** [comment]
Further info about describing responses can be found in the spec https://swagger.io/docs/specification/describing-responses/
