### ISSUE TITLE
[Not an issue] useSuspenseQuery suuport

### ISSUE THREAD

**Issue by dumbravaandrei22** [rametta/rapini#49]
What about "useSuspenseQuery" from React Query https://tanstack.com/query/v5/docs/framework/react/guides/suspense.

I didn't see any options to also generate queries that are using useSuspenseQuery instead of useQuery.
So for example, I have "useGetEntityById" but I also want to have "useGetEntityByIdSuspense" that will be the same function except that will use useSuspenseQuery. 

🙏 🙏 🙏

**Comment by rametta** [comment]
Suspense related queries are not directly supported, but the necessary ingredients are available to pass to the suspense queries if needed, such as the generated keys, requests, and types

**Comment by dumbravaandrei22** [comment]
Indeed, I was thinking the same thing after I posted this.  
Thank you a lot for the effort you made to make this great package!  🙏🙏🙏 ❤️
