### ISSUE TITLE
Support `JSON+LD` API format

### ISSUE THREAD

**Issue by TheoD02** [rametta/rapini#50]
Hello!

I wanted to run a test on our package and noticed that it lacks support for [JSON-LD](https://json-ld.org/) 😞.

I've been following the format provided by [API Platform](https://api-platform.com/docs/core/content-negotiation/).

Since I'm not very familiar with TypeScript, I'd appreciate it if someone could review this initial approach: [Comparison Link](https://github.com/rametta/rapini/compare/main...TheoD02:rapini:feat/support-json-ld?expand=1)

The change specifically focuses on surrounding type with quotes

**Comment by rametta** [comment]
Hey @TheoD02, thanks for opening the issue. I'm not familiar with JSON-LD, but I took a look at the PR and I imagine that if we decide to support that then it would be behind a flag in the CLI tool. Feel free to open a PR to us with the CLI flag and the changes and I'll take a look. Thanks!
